name: Build and Sign Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t kapil0239/nodejs:latest --push .

    - name: Install Notation
      run: |
        curl -Lo notation.tar.gz https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.1/notation_1.0.0-rc.1_linux_amd64.tar.gz
        tar -xzf notation.tar.gz
        sudo mv notation /usr/local/bin/


    - name: Import GPG Key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import -
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    # - name: Set up Notation
    #   run: |
    #     notation key import --name sample --type=pgp <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
    #     notation key passphrase --name sample --passphrase-stdin <<< "${{ secrets.GPG_PASSPHRASE }}"

    - name: Set up Notation
      run: |
        mkdir -p ~/.config/notation
        echo "${{ secrets.GPG_PASSPHRASE }}" | notation key import mykey <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
        echo "${{ secrets.GPG_PASSPHRASE }}" | notation key passphrase mykey

    - name: Sign Docker image
      run: |
        notation sign --key signing-key kapil0239/nodejs:latest
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Verify Docker image signature
      run: |
        notation verify kapil0239/nodejs:latest
